# Generated by Django 3.2.16 on 2023-02-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20230208_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16, null=True, verbose_name='Пол пользователя'),
        ),
    ]
