databases:
  - name: prototype
    databaseName: prototype
    user: prototype

services:
  - type: web
    name: prototype
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn prototype.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prototype
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
