# Generated by Django 3.2.16 on 2023-02-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
