# Generated by Django 3.2.16 on 2023-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
    ]
